apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminservice
  template:
    metadata:
      labels:
        app: adminservice
    spec:
      containers:
        - name: adminservice
          image: tavernhelios/adminservice
          ports:
            - containerPort: 5068
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5068"

            # ClickHouse
            - name: ClickHouse__Host
              value: "clickhouse-monitoring"
            - name: ClickHouse__Port
              value: "8123"
            - name: ClickHouse__Database
              value: "default"
            - name: ClickHouse__User
              value: "default"
            - name: ClickHouse__Password
              value: ""

            # RabbitMQ
            - name: RabbitMQ__Host
              value: "rabbitmq-monitoring"
            - name: RabbitMQ__Port
              value: "5672"
            - name: RabbitMQ__User
              value: "admin"
            - name: RabbitMQ__Password
              value: "admin"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: adminservice
spec:
  selector:
    app: adminservice
  ports:
    - name: web
      port: 5068
      targetPort: 5068
      nodePort: 32048 
  type: NodePort
