apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuservice
  template:
    metadata:
      labels:
        app: menuservice
    spec:
      containers:
        - name: menuservice
          image: ghcr.io/lavliet2/menuservice:latest
          ports: 
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
      imagePullSecrets:
        - name: ghcr-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: menuservice
spec:
  type: NodePort 
  selector:
    app: menuservice
  ports:
    - protocol: TCP
      port: 5041
      targetPort: 8080
      nodePort: 32041 
