apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-reservation
  template:
    metadata:
      labels:
        app: postgres-reservation
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "reservationdb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "helios"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-reservation-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-reservation
spec:
  type: NodePort
  selector:
    app: postgres-reservation
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32043


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-reservation-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

