apiVersion: apps/v1
kind: Deployment
metadata:
  name: tavernhelios-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tavernhelios-client
  template:
    metadata:
      labels:
        app: tavernhelios-client
    spec:
      containers:
        - name: tavernhelios-client
          image: ghcr.io/lavliet2/heliostavern-frontend:latest
          ports:
            - containerPort: 5041 
---
apiVersion: v1
kind: Service
metadata:
  name: tavernhelios-client-service
spec:
  selector:
    app: tavernhelios-client
  ports:
    - protocol: TCP
      port: 5041
      targetPort: 5041
  type: NodePort
  nodePort: 32041 