apiVersion: apps/v1
kind: Deployment
metadata:
  name: tavernhelios-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tavernhelios-server
  template:
    metadata:
      labels:
        app: tavernhelios-server
    spec:
      containers:
        - name: tavernhelios-server
          image: ghcr.io/lavliet2/heliostavern-backend:latest
          ports:
            - containerPort: 8080  
            - containerPort: 8081 
          env:
            - name: MENU_SERVICE_URL
              value: "http://menuservice:5041/"
      imagePullSecrets:
        - name: ghcr-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: tavernhelios-server-service
spec:
  type: NodePort
  selector:
    app: tavernhelios-server
  ports:
    - protocol: TCP
      port: 5040      
      targetPort: 8080  
      nodePort: 32040 
