apiVersion: apps/v1
kind: Deployment
metadata:
  name: tavernhelios-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tavernhelios-server
  template:
    metadata:
      labels:
        app: tavernhelios-server
    spec:
      containers:
        - name: tavernhelios-server
          image: ghcr.io/lavliet2/heliostavern-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5555  
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5555"
            - name: MENU_SERVICE_URL
              value: "http://menuservice:5064"
            - name: RESERVATION_SERVICE_URL
              value: "http://reservationservice:5065"
      imagePullSecrets:
        - name: ghcr-secret 

---
apiVersion: v1
kind: Service
metadata:
  name: tavernhelios-server-service
spec:
  type: NodePort
  selector:
    app: tavernhelios-server
  ports:
    - protocol: TCP
      port: 5555      
      targetPort: 5555  
      nodePort: 32050 
