apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tavernhelios-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - heliostavern.local
      secretName: heliostavern-tls 
  rules:
    - host: heliostavern.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tavernhelios-server-service
                port:
                  number: 8080  

          - path: /
            pathType: Prefix
            backend:
              service:
                name: tavernhelios-server-service
                port:
                  number: 8080

          - path: /menu
            pathType: Prefix
            backend:
              service:
                name: menuservice
                port:
                  number: 5064  
            nginx.ingress.kubernetes.io/backend-protocol: "GRPC"

          - path: /reservation
            pathType: Prefix
            backend:
              service:
                name: reservationservice
                port:
                  number: 5065
            nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
