services:

  adminService:
    image: tavernhelios/adminservice
    container_name: adminService
    build:
      context: .
      dockerfile: ./AdministrationService/TavernHelios.AdministrationService.AdministrationServiceServer/Dockerfile
    depends_on:
      - clickhouse
      - rabbitmq
      - prometheus
      - grafana
      - server    
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - app_network

  clickhouse:
    image: clickhouse/clickhouse-server:23.8.4.69-alpine
    container_name: clickhouse-monitoring
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    container_name: rabbitmq-monitoring
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus-monitoring
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    container_name: grafana-monitoring
    networks:
      - app_network

  mongoMenu:
    image: mongo
    container_name: mongoMenu
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: 'mongoMenu'
    networks:
      - app_network
      
  mongoLayout:
    image: mongo
    container_name: mongoLayout
    ports:
      - '27018:27017'
    volumes:
      - mongoLayout_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: 'mongoLayout'
    networks:
      - app_network

  postgresReservation:
    image: postgres:latest
    container_name: postgresReservation
    restart: always
    user: postgres
    ports:
      - "5434:5432"
    environment:
      PGUSER: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helios
    networks:
      - app_network
    volumes:
      - postgresReservation_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  menuService:
    container_name: menuService
    image: tavernhelios/menuservice 
    build:
      context: .
      dockerfile: ./MenuService/MenuServiceServer/Dockerfile
    ports:
      - '5064:5064'
    depends_on:
      - mongoMenu
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5064"
    command: ["dotnet", "MenuServiceServer.dll"]
    networks:
      - app_network
      
  layoutService:
    container_name: layoutService
    image: tavernhelios/layoutservice 
    build:
      context: .
      dockerfile: ./LayoutService/TavernHelios.LayoutService.LayoutServiceServer/Dockerfile
    ports:
      - '5066:5066'
    depends_on:
      - mongoLayout
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5066"
    command: ["dotnet", "LayoutServiceServer.dll"]
    networks:
      - app_network

  ReservationService:
    container_name: ReservationService
    image: tavernhelios/reservationservice 
    build:
      context: .
      dockerfile: ./ReservationService\TavernHelios.ReservationServiceServer/Dockerfile
    ports:
      - '5065:5065'
    depends_on:
      - postgresReservation
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5065"  
    command: ["dotnet", "TavernHelios.ReservationServiceServer.dll"]
    networks:
      - app_network

  server:
    container_name: TavernHelios.Server
    image: tavernhelios/server
    build:
      context: .
      dockerfile: ./TavernHelios.Server/Dockerfile
    ports:
      # - "5000:5000"
      - "5555:5555"

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5555"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "helios"
      # VITE_API_URL: "https://localhost:5555"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    command: ["dotnet", "TavernHelios.Server.dll"]
    networks:
      - app_network

  client:
    container_name: tavernhelios.client
    image: tavernhelios/client
    build:
      context: .
      dockerfile: ./tavernhelios.client/Dockerfile
      args:
        NODE_ENV: "development"
        VITE_API_URL: "https://localhost:5555"
    environment:
      NODE_ENV: "development"
      VITE_API_URL: "https://localhost:5555"
    ports:
      - "8888:443"
    depends_on:
      - server
    networks:
      - app_network
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      # - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      
# networks:
#   app_network:
#     driver: bridge     

volumes:
  mongo_data:
  mongoLayout_data:
  postgresReservation_data: