global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse-monitoring:9363"] # Встроенный эндпоинт ClickHouse

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
