global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aspnetcore'
    static_configs:
    # ASP.NET Core приложение доступно по адресу http://host.docker.internal:5000 (для Docker на Windows/macOS) или используйте IP-адрес контейнера.
      - targets: ['host.docker.internal:8085']  # Адрес ASP.NET Core приложения
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']  # RabbitMQ metrics endpoint
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']  # ClickHouse metrics endpoint