services:
  mongoMenuService:
    image: mongo
    container_name: mongoMenuService
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: 'mongoMenuService'

  menuService:
    container_name: menuService
    image: tavernhelios/menuservice 
    build:
      context: .
      dockerfile: ./MenuService/MenuServiceServer/Dockerfile
    ports:
      - '5064:5064'
    depends_on:
      - mongoMenuService
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5064"  
    command: ["dotnet", "TavernHelios.MenuService.MenuServiceServer.dll"]

volumes:
  mongo_data:
